"""
Mapeamento entre abas da planilha Excel e stored procedures do SQL Server.
Cada entrada define: procedure, PKUnica1/2, colunas (excel -> sql), e colunas PK.
"""

# Ordem obrigatoria de importacao (dependencias entre tabelas)
ORDEM_IMPORTACAO = [
    "EMPRESA", "FILIAL", "REPR", "PAGTO", "TRANSP",
    "ESTADOS", "FAMILIAS", "ESTILOS", "CLIENTES",
    "PAGTOFILIAL", "PRODUTOS"
]

MAPA_ABAS = {
    "EMPRESA": {
        "procedure": "ImportaConfiguracaoEmpresa",
        "pkunica1": "ImportaConfiguracaoEmpresa_PKUnica1",
        "pkunica2": "ImportaConfiguracaoEmpresa_PKUnica2",
        "finalizacao": "ConfigurarEmpresa",
        "especial": True,
    },
    "FILIAL": {
        "procedure": "ImportaFilial",
        "pkunica1": "ImportaFilial_PKUnica1",
        "pkunica2": "ImportaFilial_PKUnica2",
        "colunas": [
            ("CodFilial", "@CodFilial", "int"),
            ("Filial", "@Filial", "varchar"),
            ("TituloAdicional1", "@TituloAdicional1", "varchar"),
            ("TituloAdicional2", "@TituloAdicional2", "varchar"),
            ("Logotipo", "@Logotipo", "varchar"),
        ],
        "pk_columns": [("CodFilial", "@CodFilial", "int")],
    },
    "REPR": {
        "procedure": "ImportaRepresentante",
        "pkunica1": "ImportaRepresentante_PKUnica1",
        "pkunica2": "ImportaRepresentante_PKUnica2",
        "colunas": [
            ("CodRepresentante", "@codrepresentante", "smallint"),
            ("Representante", "@representante", "varchar"),
        ],
        "pk_columns": [("CodRepresentante", "@codrepresentante", "smallint")],
    },
    "PAGTO": {
        "procedure": "ImportaCondPagamento",
        "pkunica1": "ImportaCondPagamento_PKUnica1",
        "pkunica2": "ImportaCondPagamento_PKUnica2",
        "colunas": [
            ("CodCondPagamento", "@codcondpagamento", "smallint"),
            ("CondPagamento", "@condpagamento", "varchar"),
            ("Desconto1", "@desconto1", "decimal"),
            ("Desconto2", "@desconto2", "decimal"),
            ("Desconto3", "@desconto3", "decimal"),
            ("VlrMinimoPedido", "@vlrminimopedido", "decimal"),
            ("TipoCondPagamento", "@tipocondpagamento", "char"),
            ("CondPagamentoPadrao", "@condpagamentopadrao", "char"),
            ("VlrMinimoComEstAtual", "@vlrminimocomestatual", "char"),
            ("VlrMinimoComEstFuturo", "@vlrminimocomestfuturo", "char"),
            ("VlrMinimoComEstEsgotado", "@vlrminimocomestesgotado", "char"),
        ],
        "pk_columns": [("CodCondPagamento", "@codcondpagamento", "smallint")],
    },
    "TRANSP": {
        "procedure": "ImportaTransportadora",
        "pkunica1": "ImportaTransportadora_PKUnica1",
        "pkunica2": "ImportaTransportadora_PKUnica2",
        "colunas": [
            ("CodTransportadora", "@codtransportadora", "smallint"),
            ("Transportadora", "@transportadora", "varchar"),
            ("TransportadoraPadrao", "@transportadorapadrao", "char"),
        ],
        "pk_columns": [("CodTransportadora", "@codtransportadora", "smallint")],
    },
    "ESTADOS": {
        "procedure": "ImportaEstado",
        "pkunica1": "ImportaEstado_PKUnica1",
        "pkunica2": "ImportaEstado_PKUnica2",
        "colunas": [
            ("SiglaEstado", "@siglaestado", "char"),
            ("NomeEstado", "@nomeestado", "varchar"),
            ("Padrao", "@padrao", "tinyint"),
            ("ClienteNovoTabPreco", "@clientenovotabpreco", "tinyint"),
        ],
        "pk_columns": [("SiglaEstado", "@siglaestado", "char")],
    },
    "FAMILIAS": {
        "procedure": "ImportaFamilia",
        "pkunica1": "ImportaFamilia_PKUnica1",
        "pkunica2": "ImportaFamilia_PKUnica2",
        "colunas": [
            ("CodFamilia", "@codfamilia", "int"),
            ("Familia", "@familia", "varchar"),
            ("MultiploFamilia", "@multiplofamilia", "int"),
            ("MinimoFamilia", "@minimofamilia", "int"),
            ("DescontoFamilia", "@descontofamilia", "decimal"),
        ],
        "pk_columns": [("CodFamilia", "@codfamilia", "int")],
    },
    "ESTILOS": {
        "procedure": "ImportaEstilo",
        "pkunica1": "ImportaEstilo_PKUnica1",
        "pkunica2": "ImportaEstilo_PKUnica2",
        "colunas": [
            ("CodEstilo", "@codestilo", "int"),
            ("Estilo", "@estilo", "varchar"),
        ],
        "pk_columns": [("CodEstilo", "@codestilo", "int")],
    },
    "CLIENTES": {
        "procedure": "ImportaCliente",
        "pkunica1": "ImportaCliente_PKUnica1",
        "pkunica2": "ImportaCliente_PKUnica2",
        "colunas": [
            ("CodCliente", "@codcliente", "int"),
            ("CodRepresentante", "@codrepresentante", "smallint"),
            ("NomeFantasia", "@nomefantasia", "varchar"),
            ("RazaoSocial", "@razaosocial", "varchar"),
            ("CNPJCPF", "@cnpjcpf", "varchar"),
            ("IERG", "@ierg", "varchar"),
            ("Logradouro", "@logradouro", "varchar"),
            ("Bairro", "@bairro", "varchar"),
            ("Cidade", "@cidade", "varchar"),
            ("UF", "@uf", "char"),
            ("CEP", "@cep", "varchar"),
            ("DDD", "@ddd", "tinyint"),
            ("Telefone1", "@telefone1", "varchar"),
            ("Telefone2", "@telefone2", "varchar"),
            ("FAX", "@fax", "varchar"),
            ("NomeContato", "@nomecontato", "varchar"),
            ("NomeTransportadora", "@nometransportadora", "varchar"),
            ("Observacao", "@observacao", "varchar"),
            ("EMail", "@email", "varchar"),
            ("PrecoTabela", "@precotabela", "tinyint"),
            ("CodTransportadora", "@codtransportadora", "smallint"),
        ],
        "pk_columns": [("CodCliente", "@codcliente", "int")],
    },
    "PAGTOFILIAL": {
        "procedure": "ImportaRestricaoCondPagamento",
        "pkunica1": "ImportaRestricaoCondPagamento_PKUnica1",
        "pkunica2": "ImportaRestricaoCondPagamento_PKUnica2",
        "colunas": [
            ("CodCondPagamento", "@codcondpagamento", "smallint"),
            ("CodFilial", "@codfilial", "int"),
            ("VlrMinimoPedido", "@vlrminimopedido", "decimal"),
        ],
        "pk_columns": [
            ("CodCondPagamento", "@codcondpagamento", "smallint"),
            ("CodFilial", "@codfilial", "int"),
        ],
    },
    "PRODUTOS": {
        "procedure": "ImportaProdutoAmbos",
        "pkunica1": "ImportaProdutoAmbos_PKUnica1",
        "pkunica2": "ImportaProdutoAmbos_PKUnica2",
        "colunas": [
            ("CodProduto", "@codproduto", "varchar"),
            ("CodAuxiliarProduto", "@codauxiliarproduto", "varchar"),
            ("Produto", "@produto", "varchar"),
            ("PrecoTabela1", "@precotabela1", "decimal"),
            ("PrecoTabela2", "@precotabela2", "decimal"),
            ("PrecoTabela3", "@precotabela3", "decimal"),
            ("QtdeEstoqueAtual", "@qtdeestoqueatual", "int"),
            ("QtdeEstoqueFuturo", "@qtdeestoquefuturo", "int"),
            ("DtEstoqueFuturo", "@dtestoquefuturo", "datetime"),
            ("LimiteDescIndividual", "@limitedescindividual", "decimal"),
            ("AliquotaIPI", "@aliquotaipi", "decimal"),
            ("MultiploGrade", "@multiplograde", "int"),
            ("DescontoGrade", "@descontograde", "decimal"),
            ("PathFotografia", "@pathfotografia", "varchar"),
            ("CodFilial", "@codfilial", "int"),
            ("PrecoPromocional", "@precopromocional", "char"),
            ("TipoVendaSemEstoque", "@tipovendasemestoque", "char"),
            ("CodFamilia", "@codfamilia", "int"),
            ("CodEstilo", "@codestilo", "int"),
            ("QtdeMultipla", "@qtdemultipla", "int"),
            ("QtdeMinima", "@qtdeminima", "int"),
            ("QtdeTabela1", "@qtdetabela1", "int"),
            ("QtdeTabela2", "@qtdetabela2", "int"),
            ("QtdeTabela3", "@qtdetabela3", "int"),
            ("QtdeEtiquetas", "@qtdeetiquetas", "smallint"),
        ],
        "pk_columns": [
            ("CodProduto", "@codproduto", "varchar"),
            ("CodAuxiliarProduto", "@codauxiliarproduto", "varchar"),
        ],
    },
}
